
general {
  hide_cursor = true
  grace = 2
  ignore_empty_input = true

}

background {
  path = ~/system_repo/wallpapers/quantum_forest.png
  blur_passes = 0
}

# Left hand bar

shape {
  size = 20%, 100%

  color = rgba(36, 36, 36, 0.96)

  position = 0, 0
  halign = left
  valign = center
}

shape {
  size = 2, 100%

  color = rgb(125, 197, 31)

  position = 20%, 0
  halign = left
  valign = center
}

# Login

label {
  text = Login <b>󰍂 </b>
  font_size = 50
  font_family = JetBrains Mono Extrabold

  position = 1%, 150
  halign = left
  valign = center
}

# User

label {
  text = User:
  font_size = 16
  font_family = JetBrains Mono Extrabold

  position = 1%, 50
  halign = left
  valign = center
}

label {
  text = <b> </b>
  font_size = 20
  font_family = JetBrains Mono Extrabold

  color = rgb(125, 197, 31)

  position = 2%, 0
  halign = left
  valign = center
}

label {
  text = <b>$USER</b>
  font_size = 16
  font_family = JetBrains Mono Extrabold

  color = rgb(125, 197, 31)

  position = 8%, 0
  halign = left
  valign = center
}

input-field {
  size = 18%, 50
  outline_thickness = 2
  rounding = 16
  fade_on_empty = false
  hide_input = true

  inner_color = rgb(24, 24, 24)
  outer_color = rgb(125, 197, 31)
  font_color = rgb(125, 197, 31)

  placeholder_text = 

  position = 1%, 0
  halign = left
  valign = center
}

# Password

label {
  text = Password:
  font_size = 16
  font_family = JetBrains Mono Extrabold

  position = 1%, -80
  halign = left
  valign = center
}

label {
  text = <b>󱕴 </b>
  font_size = 20
  font_family = JetBrains Mono Extrabold

  color = rgb(125, 197, 31)

  position = 2%, -130
  halign = left
  valign = center
}

input-field {
  size = 18%, 50
  outline_thickness = 2
  rounding = 16
  fade_on_empty = false

  inner_color = rgb(24, 24, 24)
  outer_color = rgb(125, 197, 31)
  font_color = rgb(125, 197, 31)

  placeholder_text = <b>password...</b>

  position = 1%, -130
  halign = left
  valign = center
}

label {
  text = <b> </b>
  font_size = 20
  font_family = JetBrains Mono Extrabold

  color = rgb(125, 197, 31)

  position = 17.5%, -130
  halign = left
  valign = center
}

# Time

label {
  text = <i>Time: $TIME   </i>
  text_align = center
  font_size = 11
  font_family = JetBrains Mono Extrabold

  color = rgb(145, 145, 145)

  position = 13%, -170
  halign = left
  valign = center
}